FROM oven/bun:1.3.5 AS builder
WORKDIR /app
COPY package.json ./
RUN bun install
COPY . .
RUN bun run build && \
    cp -r public .next/standalone/public && \
    cp -r .next/static .next/standalone/.next/static

FROM oven/bun:1.3.5
WORKDIR /app
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
COPY --from=builder /app/.next/standalone ./
EXPOSE 3000
CMD ["bun", "server.js"]
